### ISSUE TITLE
Console error on Clients

### ISSUE THREAD

**Issue by mexikoedi** [TTT-2/ttt2-octagonal-hud#12]
I'm using the Steam Workshop version and the TTT2 Steam Workshop version.
Some Clients got an error in the console. 
I also got this error but another player not.
This error was not present in an earlier version.

Client error:
[[TTT2] Octagonal HUD [THEME]] lua/terrortown/gamemode/shared/hud_elements/ttt_killer_info_popup/octagonal_killer_info_popup.lua:48: attempt to index global 'KILLER_INFO' (a nil value)
  1. ShouldDraw - lua/terrortown/gamemode/shared/hud_elements/ttt_killer_info_popup/octagonal_killer_info_popup.lua:48
   2. DrawElemAndChildren - gamemodes/terrortown/gamemode/shared/huds/base_huds/hud_base/cl_init.lua:289
    3. Draw - gamemodes/terrortown/gamemode/shared/huds/base_huds/hud_base/cl_init.lua:332
     4. DrawHUD - gamemodes/terrortown/gamemode/client/cl_hud_manager.lua:18
      5. unknown - gamemodes/terrortown/gamemode/client/cl_hud_manager.lua:45

The weird thing is that this error disappeared after restarting the Server but I still wanted to make sure to report this because maybe there is more to this issue.

If this issue is already fixed or the restart was required to fix this because it's a "one-time-error" or something else then you can close this issue again.

**Comment by vinhill** [comment]
On our server, we observed more than just a console error. Several HUD elements, e.g. the weapon list were invisible.

**Comment by mexikoedi** [comment]
> On our server, we observed more than just a console error. Several HUD elements, e.g. the weapon list were invisible. Restarting the server did not work for us, we had to remove the addon.

Yes we also experienced this but a restart "removed" the error spamming.
For example the "Health" text is missing (because it's now an icon and the translation is gone) but I think this is a known issue and should be fixed.
I just wasn't sure if this error is known so that's why I created this issue.

**Comment by TimGoll** [comment]
Sorry it took so long! This issue was caused when you used octagonal HUD without RoundInfo installed. It is fixed now. Will release it later today
