### ISSUE TITLE
ERROR

### ISSUE THREAD

**Issue by dok441** [TTT-2/ttt2-octagonal-hud#6]
[ERROR] addons/ttt2-octagonal-hud-master/lua/terrortown/gamemode/shared/hud_elements/ttt_class_options/octagonal_classoptions.lua:100: attempt to index global 'CLASS' (a nil value)
  1. Draw - addons/ttt2-octagonal-hud-master/lua/terrortown/gamemode/shared/hud_elements/ttt_class_options/octagonal_classoptions.lua:100
   2. DrawElemAndChildren - gamemodes/terrortown/gamemode/shared/huds/base_huds/hud_base/cl_init.lua:304
    3. Draw - gamemodes/terrortown/gamemode/shared/huds/base_huds/hud_base/cl_init.lua:330
     4. DrawHUD - gamemodes/terrortown/gamemode/client/cl_hud_manager.lua:82
      5. unknown - gamemodes/terrortown/gamemode/client/cl_hud_manager.lua:121

**Comment by TimGoll** [comment]
yeah, I see this problem

**Comment by TimGoll** [comment]
So, I'm really busy right now therefore I couldn't test this. But it should fix your problem. Please let me know if reappears again
